"use client";

import { useState } from "react";
import { Clock, Sparkles, ChevronDown, ChevronUp, Mail, MessageCircle } from "lucide-react";
import { Badge } from "@/shared/components/ui/badge";
import { Button } from "@/shared/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/shared/components/ui/card";
import { Separator } from "@/shared/components/ui/separator";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/shared/components/ui/collapsible";
import type { Campaign, AISuggestion } from "@/shared/types/crm";
import { buildMailtoLink, buildWhatsAppLink, groupSuggestionsByChannel } from "../lib/message-utils";
import { formatDistanceToNow } from "date-fns";
import { ptBR } from "date-fns/locale";

interface AutoGeneratedMessagesSectionProps {
  autoMessages: Array<{
    campaignId: string;
    campaignName: string;
    suggestions: AISuggestion[];
    generatedAt: Date;
  }>;
  campaigns: Campaign[];
  leadEmail?: string;
  leadPhone?: string;
  onSendMessage: (type: string, message: string, campaignId?: string) => Promise<void>;
  sendingMessage: boolean;
}

export function AutoGeneratedMessagesSection({
  autoMessages,
  campaigns,
  leadEmail,
  leadPhone,
  onSendMessage,
  sendingMessage,
}: AutoGeneratedMessagesSectionProps) {
  const [sendingMessageId, setSendingMessageId] = useState<string | null>(null);
  const [expandedChannels, setExpandedChannels] = useState<Record<string, Set<string>>>({});

  const handleSendMessage = async (messageType: string, messageContent: string, messageId: string, campaignId: string) => {
    setSendingMessageId(messageId);
    try {
      await onSendMessage(messageType, messageContent, campaignId);
    } finally {
      setSendingMessageId(null);
    }
  };

  const toggleChannel = (campaignId: string, channel: string) => {
    setExpandedChannels((prev) => {
      const campaignChannels = prev[campaignId] || new Set();
      const newChannels = new Set(campaignChannels);
      
      if (newChannels.has(channel)) {
        newChannels.delete(channel);
      } else {
        newChannels.add(channel);
      }

      return {
        ...prev,
        [campaignId]: newChannels,
      };
    });
  };

  const isChannelExpanded = (campaignId: string, channel: string) => {
    return expandedChannels[campaignId]?.has(channel) || false;
  };

  return (
    <div className="space-y-4 pt-2">
      <p className="text-sm text-muted-foreground">
        Estas mensagens foram geradas automaticamente quando o lead foi promovido para esta etapa.
      </p>

      {autoMessages.map((autoMsg) => {
        const campaign = campaigns.find(c => c.id === autoMsg.campaignId);
        const timeAgo = formatDistanceToNow(autoMsg.generatedAt, { 
          addSuffix: true, 
          locale: ptBR 
        });

        const messagesByChannel = groupSuggestionsByChannel(autoMsg.suggestions);

        const whatsappMessages = messagesByChannel.WhatsApp || [];
        const emailMessages = messagesByChannel.Email || [];

        return (
          <Card key={autoMsg.campaignId} className="border-primary/20">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="text-base">{autoMsg.campaignName}</CardTitle>
                  <CardDescription className="flex items-center gap-2 mt-1">
                    <Clock className="w-3 h-3" />
                    Gerado {timeAgo}
                  </CardDescription>
                </div>
                {campaign && (
                  <Badge variant="outline" className="text-xs">
                    {campaign.status === "active" ? "Ativa" : "Pausada"}
                  </Badge>
                )}
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* WhatsApp Messages */}
              {whatsappMessages.length > 0 && (
                <Collapsible
                  open={isChannelExpanded(autoMsg.campaignId, "whatsapp")}
                  onOpenChange={() => toggleChannel(autoMsg.campaignId, "whatsapp")}
                >
                  <div className="space-y-2">
                    <CollapsibleTrigger asChild>
                      <Button
                        variant="ghost"
                        className="w-full justify-between p-3 h-auto hover:bg-muted/50"
                      >
                        <div className="flex items-center gap-2">
                          <MessageCircle className="w-4 h-4 text-green-600" />
                          <span className="font-medium">WhatsApp</span>
                          <Badge variant="secondary" className="ml-2">
                            {whatsappMessages.length} {whatsappMessages.length === 1 ? "opção" : "opções"}
                          </Badge>
                        </div>
                        {isChannelExpanded(autoMsg.campaignId, "whatsapp") ? (
                          <ChevronUp className="w-4 h-4" />
                        ) : (
                          <ChevronDown className="w-4 h-4" />
                        )}
                      </Button>
                    </CollapsibleTrigger>
                    <CollapsibleContent className="space-y-4 pt-2">
                      {whatsappMessages.map((suggestion, index) => {
                        const isSending = sendingMessage && sendingMessageId === suggestion.id;
                        const actionLink = buildWhatsAppLink(leadPhone, suggestion.message) || "#";

                        return (
                          <div key={suggestion.id} className="space-y-2">
                            {index > 0 && <Separator />}
                            <div className="rounded-md border bg-muted/50 p-3 text-sm">
                              <pre className="whitespace-pre-wrap font-sans text-sm">
                                {suggestion.message}
                              </pre>
                            </div>
                            <div className="flex gap-2">
                              <Button
                                size="sm"
                                variant="default"
                                onClick={() => handleSendMessage("WhatsApp", suggestion.message, suggestion.id, autoMsg.campaignId)}
                                disabled={isSending}
                                className="flex-1"
                              >
                                {isSending ? "Enviando..." : "Enviar"}
                              </Button>
                              <Button
                                size="sm"
                                variant="outline"
                                asChild
                              >
                                <a
                                  href={actionLink}
                                  target="_blank"
                                  rel="noopener noreferrer"
                                >
                                  Abrir WhatsApp
                                </a>
                              </Button>
                            </div>
                          </div>
                        );
                      })}
                    </CollapsibleContent>
                  </div>
                </Collapsible>
              )}

              {/* Email Messages */}
              {emailMessages.length > 0 && (
                <>
                  {whatsappMessages.length > 0 && <Separator />}
                  <Collapsible
                    open={isChannelExpanded(autoMsg.campaignId, "email")}
                    onOpenChange={() => toggleChannel(autoMsg.campaignId, "email")}
                  >
                    <div className="space-y-2">
                      <CollapsibleTrigger asChild>
                        <Button
                          variant="ghost"
                          className="w-full justify-between p-3 h-auto hover:bg-muted/50"
                        >
                          <div className="flex items-center gap-2">
                            <Mail className="w-4 h-4 text-blue-600" />
                            <span className="font-medium">Email</span>
                            <Badge variant="secondary" className="ml-2">
                              {emailMessages.length} {emailMessages.length === 1 ? "opção" : "opções"}
                            </Badge>
                          </div>
                          {isChannelExpanded(autoMsg.campaignId, "email") ? (
                            <ChevronUp className="w-4 h-4" />
                          ) : (
                            <ChevronDown className="w-4 h-4" />
                          )}
                        </Button>
                      </CollapsibleTrigger>
                      <CollapsibleContent className="space-y-4 pt-2">
                        {emailMessages.map((suggestion, index) => {
                          const isSending = sendingMessage && sendingMessageId === suggestion.id;
                          const actionLink = buildMailtoLink(leadEmail, suggestion.message, autoMsg.campaignName) || "#";

                          return (
                            <div key={suggestion.id} className="space-y-2">
                              {index > 0 && <Separator />}
                              <div className="rounded-md border bg-muted/50 p-3 text-sm">
                                <pre className="whitespace-pre-wrap font-sans text-sm">
                                  {suggestion.message}
                                </pre>
                              </div>
                              <div className="flex gap-2">
                                <Button
                                  size="sm"
                                  variant="default"
                                  onClick={() => handleSendMessage("Email", suggestion.message, suggestion.id, autoMsg.campaignId)}
                                  disabled={isSending}
                                  className="flex-1"
                                >
                                  {isSending ? "Enviando..." : "Enviar"}
                                </Button>
                                <Button
                                  size="sm"
                                  variant="outline"
                                  asChild
                                >
                                  <a
                                    href={actionLink}
                                    target="_self"
                                  >
                                    Abrir Email
                                  </a>
                                </Button>
                              </div>
                            </div>
                          );
                        })}
                      </CollapsibleContent>
                    </div>
                  </Collapsible>
                </>
              )}
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}
