"use client";

import { useCallback, useEffect, useState } from "react";
import { ChevronDown, ChevronUp, MessageCircle, Sparkles } from "lucide-react";
import type { Campaign, CustomField, Lead, KanbanStage, ValidationError } from "@/shared/types/crm";
import { useAISuggestions } from "../hooks/use-ai-suggestions";
import { useToast } from "@/shared/hooks/use-toast";
import { getLeadMessagesAction, saveMessageAction, type LeadMessageSent } from "../actions/messages";
import { getNextStageAfterMessage, shouldMoveToContactingStage } from "../lib/stage-utils";
import { LeadAIMessagesSection } from "./LeadAIMessagesSection";
import { MessageHistory } from "./MessageHistory";
import { Separator } from "@/shared/components/ui/separator";
import type { AISuggestion } from "../lib/message-utils";
import { AutoGeneratedMessagesSection } from "./AutoGeneratedMessagesSection";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/shared/components/ui/collapsible";
import { Button } from "@/shared/components/ui/button";
import { Badge } from "@/shared/components/ui/badge";

interface LeadMessagesTabProps {
  lead: Lead;
  campaigns: Campaign[];
  customFields?: CustomField[];
  customFieldValues?: Record<string, string>;
  initialMessages?: LeadMessageSent[];
  initialAutoGeneratedMessages?: Array<{ campaignId: string; campaignName: string; suggestions: AISuggestion[]; generatedAt: Date }>;
  onMoveLead?: (
    leadId: string,
    newStage: KanbanStage,
  ) => Promise<ValidationError[] | null>;
  onMessageSent?: () => void;
}

export function LeadMessagesTab({
  lead,
  campaigns,
  customFields,
  customFieldValues,
  initialMessages = [],
  initialAutoGeneratedMessages = [],
  onMoveLead,
  onMessageSent,
}: LeadMessagesTabProps) {
  const { toast } = useToast();
  const [sendingMessage, setSendingMessage] = useState(false);
  const [selectedCampaignId, setSelectedCampaignId] = useState<string | null>(null);
  const [messages, setMessages] = useState<LeadMessageSent[]>(initialMessages);
  const [selectedChannels, setSelectedChannels] = useState<("whatsapp" | "email")[]>(["whatsapp", "email"]);
  const [autoGeneratedMessages, setAutoGeneratedMessages] = useState<Array<{ campaignId: string; campaignName: string; suggestions: AISuggestion[]; generatedAt: Date }>>(initialAutoGeneratedMessages);
  const [isAutoMessagesOpen, setIsAutoMessagesOpen] = useState(false);
  const [isGenerateMessagesOpen, setIsGenerateMessagesOpen] = useState(false);
  const [isMessageHistoryOpen, setIsMessageHistoryOpen] = useState(false);

  // Atualizar mensagens quando initialMessages prop muda (drawer busca novas mensagens)
  useEffect(() => {
    setMessages(initialMessages);
  }, [initialMessages]);

  // Atualizar mensagens geradas automaticamente quando a prop muda
  useEffect(() => {
    setAutoGeneratedMessages(initialAutoGeneratedMessages);
  }, [initialAutoGeneratedMessages]);

  const {
    isGenerating,
    showSuggestions,
    suggestions,
    error,
    generateSuggestions,
    clearSuggestions,
  } = useAISuggestions();

  const handleGenerate = useCallback(
    (campaign: Campaign, channels: ("whatsapp" | "email")[]) => {
      setSelectedCampaignId(campaign.id);
      setSelectedChannels(channels);
      generateSuggestions(campaign, lead, customFields, customFieldValues, channels);
    },
    [lead, customFields, customFieldValues, generateSuggestions],
  );

  const handleRegenerate = useCallback(
    (campaign: Campaign, channels: ("whatsapp" | "email")[]) => {
      clearSuggestions();
      setSelectedCampaignId(campaign.id);
      setSelectedChannels(channels);
      generateSuggestions(campaign, lead, customFields, customFieldValues, channels);
    },
    [lead, customFields, customFieldValues, generateSuggestions, clearSuggestions],
  );

  const handleSendMessage = useCallback(
    async (messageType: string, messageContent: string, campaignId?: string) => {
      setSendingMessage(true);

      try {
        // Salvar mensagem no histórico
        await saveMessageAction({
          leadId: lead.id,
          workspaceId: lead.workspaceId,
          campaignId: campaignId || selectedCampaignId || undefined,
          channel: messageType.toLowerCase(),
          content: messageContent,
        });

        // Mover lead para próxima etapa se necessário
        if (onMoveLead && shouldMoveToContactingStage(lead)) {
          const nextStage = getNextStageAfterMessage(lead.stage);
          const errors = await onMoveLead(lead.id, nextStage);

          if (errors && errors.length > 0) {
            toast({
              title: "Campos obrigatórios",
              description: errors.map((e) => e.message).join(", "),
              variant: "destructive",
            });
            setSendingMessage(false);
            return;
          }
        }

        toast({
          title: "Mensagem registrada!",
          description: `Mensagem de ${messageType} registrada para ${lead.name}.`,
        });

        // Recarregar mensagens após salvar (revalidação do Next.js vai atualizar no próximo render)
        try {
          const updatedMessages = await getLeadMessagesAction(lead.id);
          setMessages(updatedMessages);
        } catch (error) {
          console.error("Error reloading messages:", error);
        }

        // Callback para atualizar UI externa
        onMessageSent?.();
      } catch (err) {
        toast({
          title: "Erro ao registrar mensagem",
          description:
            err instanceof Error ? err.message : "Não foi possível registrar a mensagem",
          variant: "destructive",
        });
      } finally {
        setSendingMessage(false);
      }
    },
    [lead, selectedCampaignId, onMoveLead, onMessageSent, toast],
  );

  return (
    <div className="space-y-6">
      {/* Mensagens pré-geradas automaticamente */}
      {autoGeneratedMessages.length > 0 && (
        <>
          <Collapsible open={isAutoMessagesOpen} onOpenChange={setIsAutoMessagesOpen}>
            <div className="space-y-2">
              <CollapsibleTrigger asChild>
                <Button
                  variant="ghost"
                  className="w-full justify-between p-3 h-auto hover:bg-muted/50"
                >
                  <div className="flex items-center gap-2">
                    <Sparkles className="w-4 h-4 text-primary" />
                    <span className="text-sm font-medium">Mensagens Geradas Automaticamente com IA</span>
                    <Badge variant="secondary" className="ml-2">
                      {autoGeneratedMessages.length} {autoGeneratedMessages.length === 1 ? "campanha" : "campanhas"}
                    </Badge>
                  </div>
                  {isAutoMessagesOpen ? (
                    <ChevronUp className="w-4 h-4" />
                  ) : (
                    <ChevronDown className="w-4 h-4" />
                  )}
                </Button>
              </CollapsibleTrigger>
              <CollapsibleContent>
                <AutoGeneratedMessagesSection
                  autoMessages={autoGeneratedMessages}
                  campaigns={campaigns}
                  leadEmail={lead.email}
                  leadPhone={lead.phone}
                  onSendMessage={(type, content, campaignId) => handleSendMessage(type, content, campaignId)}
                  sendingMessage={sendingMessage}
                />
              </CollapsibleContent>
            </div>
          </Collapsible>
          <Separator />
        </>
      )}

      {/* Seção de geração de mensagens com IA */}
      <Collapsible open={isGenerateMessagesOpen} onOpenChange={setIsGenerateMessagesOpen}>
        <div className="space-y-2">
          <CollapsibleTrigger asChild>
            <Button
              variant="ghost"
              className="w-full justify-between p-3 h-auto hover:bg-muted/50"
            >
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-primary" />
                <span className="text-sm font-medium">Gerar Mensagens com IA</span>
              </div>
              {isGenerateMessagesOpen ? (
                <ChevronUp className="w-4 h-4" />
              ) : (
                <ChevronDown className="w-4 h-4" />
              )}
            </Button>
          </CollapsibleTrigger>
          <CollapsibleContent>
            <LeadAIMessagesSection
              lead={lead}
              campaigns={campaigns}
              customFields={customFields}
              customFieldValues={customFieldValues}
              isGenerating={isGenerating}
              showSuggestions={showSuggestions}
              suggestions={suggestions}
              error={error}
              selectedChannels={selectedChannels}
              onGenerate={handleGenerate}
              onRegenerate={handleRegenerate}
              onSendMessage={handleSendMessage}
              sendingMessage={sendingMessage}
            />
          </CollapsibleContent>
        </div>
      </Collapsible>

      <Separator />

      {/* Histórico de mensagens enviadas */}
      {messages.length > 0 ? (
        <Collapsible open={isMessageHistoryOpen} onOpenChange={setIsMessageHistoryOpen}>
          <div className="space-y-2">
            <CollapsibleTrigger asChild>
              <Button
                variant="ghost"
                className="w-full justify-between p-3 h-auto hover:bg-muted/50"
              >
                <div className="flex items-center gap-2">
                  <MessageCircle className="w-4 h-4 text-primary" />
                  <span className="text-sm font-medium">Histórico de Mensagens</span>
                  <Badge variant="secondary" className="ml-2">
                    {messages.length} {messages.length === 1 ? "mensagem" : "mensagens"}
                  </Badge>
                </div>
                {isMessageHistoryOpen ? (
                  <ChevronUp className="w-4 h-4" />
                ) : (
                  <ChevronDown className="w-4 h-4" />
                )}
              </Button>
            </CollapsibleTrigger>
            <CollapsibleContent>
              <MessageHistory messages={messages} />
            </CollapsibleContent>
          </div>
        </Collapsible>
      ) : (
        <div className="text-center py-6 text-muted-foreground">
          <MessageCircle className="h-10 w-10 mx-auto mb-2 opacity-40" />
          <p className="text-sm">Nenhuma mensagem enviada ainda.</p>
          <p className="text-xs mt-1">As mensagens enviadas aparecerão aqui.</p>
        </div>
      )}
    </div>
  );
}
